blank_issues_enabled: false
contact_links:
  - name: ðŸ’¡ Feature Request
    url: https://github.com/HimanshuHegde/react-epic-trails-ds/discussions/new?category=ideas
    about: If you have a feature request, please start a new discussion in the "Ideas" category.

  - name: ðŸ’¬ General Discussions & Help
    url: https://github.com/HimanshuHegde/react-epic-trails-ds/discussions
    about: Need help or have questions? Join the discussions and ask your queries here.
